### ISSUE TITLE
license mismatch

### ISSUE THREAD

**Issue by willnorris** [todogroup/ospo101#24]
The README file mentions a CC-BY license, but the LICENSE file has an Apache 2.0 license.  I would guess that CC-BY is correct?

**Comment by caniszczyk** [comment]
@willnorris update documentation and added a LICENSE-DOCS
https://github.com/todogroup/ospo101/commit/c95ac61346f7f9d94a40ca9ecff0991cd664e21c

Essentially all code is Apache 2.0 and docs is CC-BY 4.0 via the TODO Group charter. However people want to determine what is code vs docs, I can leave that as an exercise to the reader as I've come across folks that have claimed .md files are code etc, but in the end both licenses are essentially permissive and similar in spirit.
