### ISSUE TITLE
ospo101/module4 image1.png not correct

### ISSUE THREAD

**Issue by winterrocks** [todogroup/ospo101#8]
Hi,
To me it seems that module4 first image ([image1.png](https://github.com/todogroup/ospo101/blob/main/module4/image1.png)) is not correct. The current module4/image1 is "Membership Life Cycle for Online Communities" and the text talks about:
> As you can see from this graphic, ‘requirements’ generally come in the form of ‘feature requests’ from users or developers, and due to the more iterative/Agile nature of development (more on that shortly), there isn’t a long, protracted requirements phase for open source software development.

**Comment by tisonkun** [comment]
All photos under that page is disordered.

**Comment by tisonkun** [comment]
I'm working on this issue.

**Comment by winterrocks** [comment]
Perfect, I noticed also that at least some of the following pics were out of place and that of course made it a bit tricky to follow the module.

**Comment by tisonkun** [comment]
@winterrocks yep. I notice some issue on other module. But let's focus on this issue first. I'll appreciate if you can help on reviewing #9 .

**Comment by winterrocks** [comment]
I went through Module 4 again. Now pics seem to be correct ones and in correct places. There were some issues with markup and I created a new issue that should be an easy fix.
